---
version: "3.9"
services:
  dev-postgres:
    image: postgres:14.3
    volumes:
      - ./var/dev-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
